//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Puntaje
    {
        [Key]
        public int IdPuntaje { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> Puntos { get; set; }
        public string Dificultad { get; set; }
        public Nullable<System.DateTime> FechaPuntaje { get; set; }
    }
}
